import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useForm } from 'react-hook-form';
import { VehicleStatus, VehicleCondition, } from '@car-dealership/shared-types';
import { ModalForm } from '../shared/ModalForm';
export const VehicleForm = ({ vehicle, onSubmit, onCancel, isLoading, }) => {
    const { register, handleSubmit, formState: { errors }, } = useForm({
        defaultValues: vehicle || {
            status: VehicleStatus.AVAILABLE,
            condition: VehicleCondition.USED,
        },
    });
    return (_jsxs(ModalForm, { title: vehicle ? 'Edit Vehicle' : 'Add New Vehicle', onCancel: onCancel, onSubmit: handleSubmit(onSubmit), submitLabel: vehicle ? 'Update Vehicle' : 'Add Vehicle', isLoading: isLoading, children: [_jsxs("div", { className: "grid grid-cols-2 gap-4", children: [_jsxs("div", { children: [_jsx("label", { className: "label", children: "VIN *" }), _jsx("input", { ...register('vin', { required: 'VIN is required' }), className: "input", placeholder: "1HGCM82633A123456" }), errors.vin && (_jsx("p", { className: "text-red-600 text-sm mt-1", children: errors.vin.message }))] }), _jsxs("div", { children: [_jsx("label", { className: "label", children: "Make *" }), _jsx("input", { ...register('make', { required: 'Make is required' }), className: "input", placeholder: "Honda" }), errors.make && (_jsx("p", { className: "text-red-600 text-sm mt-1", children: errors.make.message }))] }), _jsxs("div", { children: [_jsx("label", { className: "label", children: "Model *" }), _jsx("input", { ...register('model', { required: 'Model is required' }), className: "input", placeholder: "Accord" }), errors.model && (_jsx("p", { className: "text-red-600 text-sm mt-1", children: errors.model.message }))] }), _jsxs("div", { children: [_jsx("label", { className: "label", children: "Year *" }), _jsx("input", { type: "number", ...register('year', {
                                    required: 'Year is required',
                                    min: { value: 1900, message: 'Invalid year' },
                                    max: { value: 2100, message: 'Invalid year' },
                                }), className: "input", placeholder: "2023" }), errors.year && (_jsx("p", { className: "text-red-600 text-sm mt-1", children: errors.year.message }))] }), _jsxs("div", { children: [_jsx("label", { className: "label", children: "Color *" }), _jsx("input", { ...register('color', { required: 'Color is required' }), className: "input", placeholder: "Silver" }), errors.color && (_jsx("p", { className: "text-red-600 text-sm mt-1", children: errors.color.message }))] }), _jsxs("div", { children: [_jsx("label", { className: "label", children: "Mileage" }), _jsx("input", { type: "number", ...register('mileage', { valueAsNumber: true }), className: "input", placeholder: "15000" })] }), _jsxs("div", { children: [_jsx("label", { className: "label", children: "Price *" }), _jsx("input", { type: "number", step: "0.01", ...register('price', {
                                    required: 'Price is required',
                                    valueAsNumber: true,
                                }), className: "input", placeholder: "28500.00" }), errors.price && (_jsx("p", { className: "text-red-600 text-sm mt-1", children: errors.price.message }))] }), _jsxs("div", { children: [_jsx("label", { className: "label", children: "Cost" }), _jsx("input", { type: "number", step: "0.01", ...register('cost', { valueAsNumber: true }), className: "input", placeholder: "25000.00" })] }), _jsxs("div", { children: [_jsx("label", { className: "label", children: "Status *" }), _jsxs("select", { ...register('status'), className: "input", children: [_jsx("option", { value: VehicleStatus.AVAILABLE, children: "Available" }), _jsx("option", { value: VehicleStatus.SOLD, children: "Sold" }), _jsx("option", { value: VehicleStatus.RESERVED, children: "Reserved" }), _jsx("option", { value: VehicleStatus.MAINTENANCE, children: "Maintenance" })] })] }), _jsxs("div", { children: [_jsx("label", { className: "label", children: "Condition" }), _jsxs("select", { ...register('condition'), className: "input", children: [_jsx("option", { value: "", children: "Select condition" }), _jsx("option", { value: VehicleCondition.NEW, children: "New" }), _jsx("option", { value: VehicleCondition.USED, children: "Used" }), _jsx("option", { value: VehicleCondition.CERTIFIED_PRE_OWNED, children: "Certified Pre-Owned" })] })] }), _jsxs("div", { children: [_jsx("label", { className: "label", children: "Transmission" }), _jsx("input", { ...register('transmission'), className: "input", placeholder: "Automatic" })] }), _jsxs("div", { children: [_jsx("label", { className: "label", children: "Fuel Type" }), _jsx("input", { ...register('fuelType'), className: "input", placeholder: "Gasoline" })] }), _jsxs("div", { children: [_jsx("label", { className: "label", children: "Body Type" }), _jsx("input", { ...register('bodyType'), className: "input", placeholder: "Sedan" })] }), _jsxs("div", { children: [_jsx("label", { className: "label", children: "Engine" }), _jsx("input", { ...register('engine'), className: "input", placeholder: "2.0L I4" })] })] }), _jsxs("div", { children: [_jsx("label", { className: "label", children: "Description" }), _jsx("textarea", { ...register('description'), className: "input", rows: 3, placeholder: "Additional details about the vehicle..." })] })] }));
};
//# sourceMappingURL=VehicleForm.js.map