import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Edit, Trash2, Car } from 'lucide-react';
import clsx from 'clsx';
const statusColors = {
    available: 'bg-green-100 text-green-800',
    sold: 'bg-gray-100 text-gray-800',
    reserved: 'bg-yellow-100 text-yellow-800',
    maintenance: 'bg-red-100 text-red-800',
};
export const VehicleCard = ({ vehicle, onEdit, onDelete }) => {
    return (_jsxs("div", { className: "card hover:shadow-md transition-shadow", children: [_jsxs("div", { className: "flex items-start justify-between mb-4", children: [_jsxs("div", { className: "flex items-center space-x-3", children: [_jsx("div", { className: "bg-primary-100 p-3 rounded-lg", children: _jsx(Car, { className: "h-6 w-6 text-primary-600" }) }), _jsxs("div", { children: [_jsxs("h3", { className: "text-lg font-semibold text-gray-900", children: [vehicle.year, " ", vehicle.make, " ", vehicle.model] }), _jsxs("p", { className: "text-sm text-gray-500", children: ["VIN: ", vehicle.vin] })] })] }), _jsx("span", { className: clsx('px-3 py-1 rounded-full text-xs font-medium capitalize', statusColors[vehicle.status]), children: vehicle.status })] }), _jsxs("div", { className: "grid grid-cols-2 gap-4 mb-4", children: [_jsxs("div", { children: [_jsx("p", { className: "text-sm text-gray-500", children: "Price" }), _jsxs("p", { className: "text-lg font-semibold text-gray-900", children: ["$", vehicle.price.toLocaleString()] })] }), vehicle.mileage && (_jsxs("div", { children: [_jsx("p", { className: "text-sm text-gray-500", children: "Mileage" }), _jsxs("p", { className: "text-lg font-semibold text-gray-900", children: [vehicle.mileage.toLocaleString(), " mi"] })] }))] }), _jsxs("div", { className: "flex flex-wrap gap-2 mb-4", children: [vehicle.condition && (_jsx("span", { className: "px-2 py-1 bg-gray-100 text-gray-700 rounded text-xs capitalize", children: vehicle.condition.replace('_', ' ') })), vehicle.transmission && (_jsx("span", { className: "px-2 py-1 bg-gray-100 text-gray-700 rounded text-xs", children: vehicle.transmission })), vehicle.fuelType && (_jsx("span", { className: "px-2 py-1 bg-gray-100 text-gray-700 rounded text-xs", children: vehicle.fuelType }))] }), _jsxs("div", { className: "flex space-x-2 pt-4 border-t border-gray-200", children: [_jsxs("button", { onClick: () => onEdit(vehicle), className: "flex-1 btn btn-secondary flex items-center justify-center space-x-2", children: [_jsx(Edit, { className: "h-4 w-4" }), _jsx("span", { children: "Edit" })] }), _jsxs("button", { onClick: () => onDelete(vehicle), className: "flex-1 btn btn-danger flex items-center justify-center space-x-2", children: [_jsx(Trash2, { className: "h-4 w-4" }), _jsx("span", { children: "Delete" })] })] })] }));
};
//# sourceMappingURL=VehicleCard.js.map