import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import { Clock } from 'lucide-react';
export const RecentVehiclesTable = ({ vehicles }) => {
    return (_jsxs("div", { className: "mt-8 card", children: [_jsxs("div", { className: "flex items-center justify-between mb-6", children: [_jsxs("div", { className: "flex items-center space-x-2", children: [_jsx(Clock, { className: "h-6 w-6 text-primary-600" }), _jsx("h2", { className: "text-xl font-bold text-gray-900", children: "Recently Added Vehicles" })] }), _jsx(Link, { to: "/vehicles", className: "text-sm font-medium text-primary-600 hover:text-primary-700", children: "View All" })] }), _jsx("div", { className: "overflow-x-auto", children: _jsxs("table", { className: "min-w-full divide-y divide-gray-200", children: [_jsx("thead", { children: _jsxs("tr", { children: [_jsx("th", { className: "px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider", children: "Vehicle" }), _jsx("th", { className: "px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider", children: "VIN" }), _jsx("th", { className: "px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider", children: "Price" }), _jsx("th", { className: "px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider", children: "Status" }), _jsx("th", { className: "px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider", children: "Added" })] }) }), _jsxs("tbody", { className: "bg-white divide-y divide-gray-200", children: [vehicles?.map((vehicle) => (_jsxs("tr", { className: "hover:bg-gray-50", children: [_jsx("td", { className: "px-4 py-4 whitespace-nowrap", children: _jsxs("div", { className: "text-sm font-medium text-gray-900", children: [vehicle.year, " ", vehicle.make, " ", vehicle.model] }) }), _jsx("td", { className: "px-4 py-4 whitespace-nowrap text-sm text-gray-500 font-mono", children: vehicle.vin }), _jsxs("td", { className: "px-4 py-4 whitespace-nowrap text-sm font-bold text-gray-900", children: ["$", vehicle.price.toLocaleString()] }), _jsx("td", { className: "px-4 py-4 whitespace-nowrap", children: _jsx("span", { className: `px-2 inline-flex text-xs leading-5 font-semibold rounded-full ${vehicle.status === 'available'
                                                    ? 'bg-green-100 text-green-800'
                                                    : vehicle.status === 'sold'
                                                        ? 'bg-gray-100 text-gray-800'
                                                        : 'bg-yellow-100 text-yellow-800'}`, children: vehicle.status }) }), _jsx("td", { className: "px-4 py-4 whitespace-nowrap text-sm text-gray-500", children: new Date(vehicle.createdAt).toLocaleDateString() })] }, vehicle.id))), (!vehicles || vehicles.length === 0) && (_jsx("tr", { children: _jsx("td", { colSpan: 5, className: "px-4 py-8 text-center text-gray-500", children: "No vehicles found" }) }))] })] }) })] }));
};
//# sourceMappingURL=RecentVehiclesTable.js.map