import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useForm } from 'react-hook-form';
import { ModalForm } from '../shared/ModalForm';
export const CustomerForm = ({ customer, onSubmit, onCancel, isLoading, }) => {
    const { register, handleSubmit, formState: { errors }, } = useForm({
        defaultValues: customer,
    });
    return (_jsxs(ModalForm, { title: customer ? 'Edit Customer' : 'Add New Customer', onCancel: onCancel, onSubmit: handleSubmit(onSubmit), submitLabel: customer ? 'Update Customer' : 'Add Customer', isLoading: isLoading, children: [_jsxs("div", { className: "grid grid-cols-2 gap-4", children: [_jsxs("div", { children: [_jsx("label", { className: "label", children: "First Name *" }), _jsx("input", { ...register('firstName', { required: 'First name is required' }), className: "input", placeholder: "John" }), errors.firstName && (_jsx("p", { className: "text-red-600 text-sm mt-1", children: errors.firstName.message }))] }), _jsxs("div", { children: [_jsx("label", { className: "label", children: "Last Name *" }), _jsx("input", { ...register('lastName', { required: 'Last name is required' }), className: "input", placeholder: "Doe" }), errors.lastName && (_jsx("p", { className: "text-red-600 text-sm mt-1", children: errors.lastName.message }))] }), _jsxs("div", { children: [_jsx("label", { className: "label", children: "Email" }), _jsx("input", { type: "email", ...register('email'), className: "input", placeholder: "john.doe@example.com" })] }), _jsxs("div", { children: [_jsx("label", { className: "label", children: "Phone" }), _jsx("input", { type: "tel", ...register('phone'), className: "input", placeholder: "555-0123" })] })] }), _jsxs("div", { children: [_jsx("label", { className: "label", children: "Address" }), _jsx("input", { ...register('address'), className: "input", placeholder: "123 Main St" })] }), _jsxs("div", { className: "grid grid-cols-3 gap-4", children: [_jsxs("div", { children: [_jsx("label", { className: "label", children: "City" }), _jsx("input", { ...register('city'), className: "input", placeholder: "Springfield" })] }), _jsxs("div", { children: [_jsx("label", { className: "label", children: "State" }), _jsx("input", { ...register('state'), className: "input", placeholder: "IL" })] }), _jsxs("div", { children: [_jsx("label", { className: "label", children: "ZIP Code" }), _jsx("input", { ...register('zipCode'), className: "input", placeholder: "62701" })] })] }), _jsxs("div", { children: [_jsx("label", { className: "label", children: "Notes" }), _jsx("textarea", { ...register('notes'), className: "input", rows: 3, placeholder: "Additional notes about the customer..." })] })] }));
};
//# sourceMappingURL=CustomerForm.js.map